version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: switchbot-backend
    ports:
      - "8000:8000"
    environment:
      - DJANGO_DEBUG=false
      - CORS_ALLOWED_ORIGINS=http://frontend:3000
    volumes:
    # ホスト側に DB ディレクトリを用意して永続化する
    - ./my-switchbot-backend/db-data/db.sqlite3:/app/db.sqlite3

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: switchbot-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_BASE_URL=http://backend:8000

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: switchbot-nginx
    ports:
      - "80:80"
    environment:
      - FRONTEND_URL=http://frontend:3000
      - BACKEND_URL=http://backend:8000
    depends_on:
      - backend
      - frontend