services:
  db:
    image: mysql:8.0
    container_name: switchbot-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: switchbot_db
      MYSQL_USER: switchbot_user
      MYSQL_PASSWORD: switchbot_pass
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: switchbot-backend
    ports:
      - "8000:8000"
    environment:
      - DJANGO_PRODUCTION=true
      - CORS_ALLOWED_ORIGINS=http://frontend:3000
      - DB_ENGINE=django.db.backends.mysql
      - DB_NAME=switchbot_db
      - DB_USER=switchbot_user
      - DB_PASSWORD=switchbot_pass
      - DB_HOST=db
      - DB_PORT=3306
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_BASE_URL: ""
    container_name: switchbot-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_BASE_URL=

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: switchbot-nginx
    ports:
      - "80:80"
    environment:
      - FRONTEND_URL=http://frontend:3000
      - BACKEND_URL=http://backend:8000
    depends_on:
      - backend
      - frontend

volumes:
  db_data: